In [56]:
from envs.robot_arm_env import RobotArmEnvironment
from gymnasium.envs.registration import register
import xml.etree.ElementTree as ET
import numpy as np
from time import sleep

In [30]:
register(id="PhysicalFetchPickAndPlaceDense-v0",
         entry_point="envs.physical_fetch_env:PhysicalObstacleFetchPickAndPlaceEnv",
         kwargs={"reward_type": "dense"})

In [66]:
def run_single_episode(robot_env,
                       scenario_seed):

    observation, info = robot_env.reset(seed=scenario_seed)
    actions = (np.random.random((100, 4)) - 0.5) * 2
    for i in range(100):
        sleep(0.1)
        action = actions[i]
        observation, reward, done, terminated, truncated, info = robot_env.step(action)
        print(observation["observation"][:3])

        if done:
            break

In [67]:
def get_positions_from_xy(x, y):
    return round(1.075 + x * 0.05, 5), round(0.525 + y * 0.05, 5)

In [68]:
def put_obstacle(x, y):
    assert 0 <= x <= 9
    assert 0 <= y <= 9
    tree = ET.parse('./assets/fetch/pick_and_place_obstacles.xml')
    root = tree.findall("worldbody")[0]
    obstacle = None
    for node in root.findall("body"):
        if node.get("name") == "obstacle_1":
            obstacle = node
            break
    x, y = get_positions_from_xy(x, y)
    obstacle.set("pos", f"{x} {y} {0.425}")
    tree.write("./assets/fetch/pick_and_place_obstacles.xml")


In [69]:
def set_goal_position(x, y):
    with open("./goal.txt", "w") as f:
        x, y = get_positions_from_xy(x, y)
        f.write(f"{x} {y} {0.425}\n")

In [70]:
def set_target_position(x, y):
    with open("./target.txt", "w") as f:
        x, y = get_positions_from_xy(x, y)
        f.write(f"{x} {y} {0.425}\n")

In [71]:
put_obstacle(9, 9)

In [72]:
set_target_position(0, 0)

In [73]:
set_target_position(0, 9)

In [74]:
put_obstacle(9, 9)
robot_env = RobotArmEnvironment(env_name="PhysicalFetchPickAndPlaceDense-v0",
                                render_mode="human")
env = robot_env.setup()


run_single_episode(robot_env, 10)
robot_env.close()


[1.36011478 0.77014898 0.53008476]
[1.38769158 0.78661745 0.54896414]
[1.41970591 0.815311   0.56961841]
[1.41012527 0.80514419 0.58859312]
[1.38920205 0.79167174 0.56515595]
[1.3692599  0.80197726 0.56911457]
[1.35175639 0.81904522 0.57709183]
[1.33899132 0.80122543 0.58621777]
[1.33741503 0.81662724 0.60054014]
[1.3255523  0.78871167 0.62282259]
[1.32208197 0.80100029 0.63207213]
[1.31786641 0.80126451 0.60737498]
[1.34092552 0.83006613 0.6058767 ]
[1.31623483 0.81184366 0.58572287]
[1.28668198 0.79846637 0.56334169]
[1.30402605 0.7968591  0.54891117]
[1.29134892 0.78068311 0.54728189]
[1.31895492 0.77135853 0.57251431]
[1.32335182 0.78442051 0.58674368]
[1.34180855 0.77160141 0.56419952]
[1.32580821 0.75398883 0.54958703]
[1.29681187 0.7402491  0.57444096]
[1.2764765  0.76837729 0.60153029]
[1.25596442 0.75398898 0.59523743]
[1.2395126  0.77741206 0.58328032]
[1.26896618 0.79582443 0.57026458]
[1.24699661 0.76826399 0.55819183]
[1.25534626 0.79486543 0.56742695]
[1.26418801 0.802540